      - name: Build Plugins
        run: |
          cd src
          ./gradlew make makePluginsJson --stacktrace --no-daemon

          find . -name "*.cs3" -exec cp {} "$GITHUB_WORKSPACE/builds" \;

          cp -f build/plugins.json "$GITHUB_WORKSPACE/builds" || echo "plugins.json bulunamadı"

          cd "$GITHUB_WORKSPACE/builds"

          if [ -f "plugins.json" ]; then
            python3 << 'EOF'
import json

order = [
    "iconUrl",
    "apiVersion",
    "repositoryUrl",
    "fileSize",
    "status",
    "language",
    "authors",
    "tvTypes",
    "version",
    "internalName",
    "description",
    "url",
    "name"
]

with open("plugins.json", "r", encoding="utf-8") as f:
    data = json.load(f)

ordered = []

for item in data:
    item.pop("fileHash", None)

    sorted_item = {
        k: item[k]
        for k in order
        if k in item
    }

    for k, v in item.items():
        if k not in sorted_item:
            sorted_item[k] = v

    ordered.append(sorted_item)

with open("plugins.json", "w", encoding="utf-8") as f:
    json.dump(
        ordered,
        f,
        indent=4,
        ensure_ascii=False
    )

print("plugins.json temizlendi.")
EOF
          fi
